<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Aerospace</name>
   <tag></tag>
   <elementGuidId>b56eedba-de70-4af1-ba2d-105601688063</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aerospace</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/div[@class=&quot;global-container&quot;]/div[@class=&quot;container-main&quot;]/app-register[1]/div[@class=&quot;container-main login-layout-component user-reg-section&quot;]/div[@class=&quot;login-container container-fluid&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-xs-12 col-sm-6 col-md-8&quot;]/div[@class=&quot;row login-form-wrapper&quot;]/div[@class=&quot;reg-form-wrapper&quot;]/form[@class=&quot;ng-invalid ng-dirty ng-touched&quot;]/div[@class=&quot;form-box&quot;]/div[@class=&quot;row border-btm margin-0&quot;]/div[@class=&quot;form-group col-sm-12 col-md-4 padding-0&quot;]/div[@class=&quot;dropdown-wrapper&quot;]/div[@class=&quot;dropdown dropdown-canvas open&quot;]/ul[@class=&quot;dropdown-menu max-dropdown-menu&quot;]/li[1]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
